/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entidades.Autor;
import entidades.Editora;
import entidades.Livro;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NAutor;
import negocio.NEditora;
import negocio.NLivro;
import util.RenderizaLabel;

/**
 *
 * @author repez
 */
public class FrmPesLivro extends javax.swing.JInternalFrame {
    
    JDesktopPane painelPrincipal;

    /**
     * Creates new form FrmPesLivro
     */
    public FrmPesLivro() {
        initComponents();
        carregarTabela();
    }
    
    public FrmPesLivro(JDesktopPane painelPrincipal) {
        this();
        this.painelPrincipal = painelPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setTitle("Pesquisa de Livro");

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBN", "Título", "Autor", "Editora", "Capa"
            }
        ));
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);
        if (tblResultado.getColumnModel().getColumnCount() > 0) {
            tblResultado.getColumnModel().getColumn(0).setMinWidth(20);
        }

        jButton1.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadoMousePressed
        try {
            int linhaSelecionada = tblResultado.getSelectedRow();
            String id = tblResultado.getValueAt(linhaSelecionada, 0).toString();
            System.out.println(id);
            FrmCadLivro frmCadLivro = new FrmCadLivro(painelPrincipal, id);
            painelPrincipal.add(frmCadLivro);
            frmCadLivro.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tblResultadoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {
            
            DefaultTableModel modelo = (DefaultTableModel) tblResultado.getModel();
            
            NLivro nl = new NLivro();
            ArrayList<Livro> listaLivros = nl.listar();            
            
            //setando o modo de renderizacão da coluna Capa da tabela
            tblResultado.getColumn("Capa").setCellRenderer(new RenderizaLabel());
            
            modelo.setNumRows(listaLivros.size());
            
            NAutor na = new NAutor();
            NEditora ne = new NEditora();
            
            for (int i = 0; i < listaLivros.size(); i++) {
                Livro liv = listaLivros.get(i);
                modelo.setValueAt(liv.getId(), i, 0);
                modelo.setValueAt(liv.getIsbn(), i, 1);
                modelo.setValueAt(liv.getTitulo(), i, 2);   
                
                Autor a = na.consultar(liv.getAutor().getId());
                modelo.setValueAt(a.getNome(), i, 3);
                
                Editora e = ne.consultar(liv.getEditora().getId());            
                modelo.setValueAt(e.getNome(), i, 4);
                   
                ImageIcon foto = new ImageIcon(liv.getFotoDaCapa());
                Image imagem = foto.getImage();
                Image novaImagem = imagem.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                ImageIcon fotoRedimensionada = new ImageIcon(novaImagem);
                    
                JLabel img = new JLabel();
                img.setIcon(fotoRedimensionada);
                
                modelo.setValueAt(img, i, 5);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
