/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author repez
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optAutor = new javax.swing.JMenuItem();
        optCliente = new javax.swing.JMenuItem();
        optEditora = new javax.swing.JMenuItem();
        optExemplar = new javax.swing.JMenuItem();
        optLivro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        optSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        optAutor.setText("Autor");
        optAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAutorActionPerformed(evt);
            }
        });
        jMenu1.add(optAutor);

        optCliente.setText("Cliente");
        optCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optClienteActionPerformed(evt);
            }
        });
        jMenu1.add(optCliente);

        optEditora.setText("Editora");
        optEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEditoraActionPerformed(evt);
            }
        });
        jMenu1.add(optEditora);

        optExemplar.setText("Exemplar");
        optExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optExemplarActionPerformed(evt);
            }
        });
        jMenu1.add(optExemplar);

        optLivro.setText("Livro");
        optLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optLivroActionPerformed(evt);
            }
        });
        jMenu1.add(optLivro);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Sair");

        optSair.setText("Sair");
        optSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSairActionPerformed(evt);
            }
        });
        jMenu3.add(optSair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAutorActionPerformed
        try {
            FrmCadAutor frmCadAutor = new FrmCadAutor(painelPrincipal);
            painelPrincipal.add(frmCadAutor);
            frmCadAutor.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_optAutorActionPerformed

    private void optSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSairActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_optSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_formWindowClosing

    private void optEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEditoraActionPerformed
        try {
            FrmCadEditora frmCadEditora = new FrmCadEditora(painelPrincipal);
            painelPrincipal.add(frmCadEditora);
            frmCadEditora.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_optEditoraActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void optLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optLivroActionPerformed
        try {
            FrmCadLivro frmCadLivro = new FrmCadLivro(painelPrincipal);
            painelPrincipal.add(frmCadLivro);
            frmCadLivro.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_optLivroActionPerformed

    private void optClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optClienteActionPerformed
        try {
            FrmCadCliente frmCadCliente = new FrmCadCliente(painelPrincipal);
            painelPrincipal.add(frmCadCliente);
            frmCadCliente.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        
    }//GEN-LAST:event_optClienteActionPerformed

    private void optExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optExemplarActionPerformed
        try {
            FrmCadExemplar frmCadExemplar = new FrmCadExemplar(painelPrincipal);
            painelPrincipal.add(frmCadExemplar);
            frmCadExemplar.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }    
    }//GEN-LAST:event_optExemplarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem optAutor;
    private javax.swing.JMenuItem optCliente;
    private javax.swing.JMenuItem optEditora;
    private javax.swing.JMenuItem optExemplar;
    private javax.swing.JMenuItem optLivro;
    private javax.swing.JMenuItem optSair;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables

    private void sair() {
        try {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja mesmo sair?", "libraryControl", JOptionPane.YES_NO_OPTION);
            if(resposta == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
